## Principal Component Analysis (PCA)

In [11]:
import psycopg2
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

In [3]:
# ParÃ¡metros de conexiÃ³n
param_dic = {
    "host"      : "localhost",
    "database"  : "cancerdb",
    "user"      : "manu",
    "password"  : "foo"
}

# ConexiÃ³n e importanciÃ³n de datos desde la base.
conn = psycopg2.connect(**param_dic)
df = pd.read_sql_query('SELECT * FROM esophageal_clean',con=conn)
df

,id_esophageal,region,age,sex,alcohol,tobacco,family_history,diff_swallowing,pain_swallowing,weight_loss,...,adj_organ,tnm_stage,surgery,t_hital_eso,t_thoracic_eso,chemotherapy,radiotherapy,hospital_stay,status_patient,khat
0,1,OROMIA,66,0,1,1,1,0,0,1,...,7,2,0,1,1,0,0,1,1,1
1,2,ADDIS ABABA,66,1,1,1,1,0,1,0,...,7,0,1,0,1,0,0,1,1,0
2,3,ADDIS ABABA,62,1,0,0,1,0,1,1,...,2,3,0,1,1,1,0,1,1,0
3,4,OROMIA,62,1,0,1,1,0,1,0,...,3,3,1,0,1,1,0,16,1,1
4,5,OROMIA,45,0,1,1,1,0,1,1,...,7,4,0,1,1,0,0,8,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,345,OROMIA,55,1,1,1,1,0,1,1,...,7,4,1,0,1,0,0,1,1,0
345,346,SNNPR,45,0,1,1,1,0,1,1,...,7,2,1,0,1,0,0,2,0,1
346,347,ADDIS ABABA,67,1,1,1,1,0,1,1,...,7,3,1,1,1,0,0,1,0,0
347,348,OROMIA,32,0,1,1,1,0,1,1,...,7,4,1,1,1,0,0,2,1,1
348,349,AMHARA,58,1,0,0,1,0,1,1,...,4,3,1,1,1,0,0,3,1,0

In [5]:
X = df.drop(columns=['status_patient','id_esophageal','region'])
y = df['status_patient']

In [13]:
scaler = MinMaxScaler()
data_rescaled = scaler.fit_transform(X)

In [21]:
pca = PCA(n_components = 0.95)
pca.fit(data_rescaled)
reduced = pca.transform(data_rescaled)
ndf = pd.DataFrame(reduced)
ndf

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.507395,-0.421142,0.387359,-0.278536,-0.256417,-0.142587,0.524002,-0.058740,0.692328,-0.513301,0.578816,-0.154673,-0.372326,0.063447,0.203476,-0.029339,0.080054,0.230352,0.796531,-0.240772
1,-0.913338,0.469680,-0.897301,0.516064,0.090262,0.497239,0.621075,-0.086860,0.133382,0.429461,-0.143149,-0.458448,0.374120,-0.158740,-0.016830,-0.390028,-0.169044,-0.279533,0.069854,0.036733
2,0.941651,1.135893,-0.037524,-0.773436,-0.164629,0.358867,-0.304602,-0.485169,-0.876215,-0.409627,0.024798,0.077079,0.381671,-0.126444,0.175365,0.071274,0.162689,0.224261,0.033812,0.427166
3,-0.485110,0.951573,-0.114926,0.300021,0.658008,-0.455769,-0.727300,-0.448736,-0.416970,-0.108712,-0.416662,-0.129338,0.247061,-0.112766,-0.044348,0.193446,-0.194722,-0.257878,0.049161,-0.170757
4,0.601519,-0.528808,0.330653,-0.170536,-0.526976,-0.289042,0.376571,0.071930,0.079052,0.315951,0.504512,-0.333416,0.457902,0.236440,-0.114730,-0.240092,-0.016232,-0.234302,-0.079925,0.217646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,-0.715636,0.844186,0.210698,-0.527063,-0.621953,0.545056,0.055477,0.114063,0.486307,-0.182243,0.387782,-0.338829,-0.401306,0.086131,0.039344,-0.104345,-0.041844,-0.050511,-0.155663,-0.145967
345,-0.761061,-0.283822,0.736366,-0.275418,-0.178385,-0.129462,0.489464,0.128567,0.204991,-0.060175,-0.223519,-0.086530,0.095372,0.038188,0.047724,0.024195,0.038740,-0.036529,0.005869,0.089886
346,-0.172933,0.545468,-0.276553,-0.631550,-0.470432,0.603202,0.171805,0.638355,0.791530,-0.395017,0.630845,0.043759,-0.170708,-0.105080,0.269490,0.272448,0.049849,-0.268003,-0.048852,-0.063767
347,-0.069601,-0.202773,0.713319,-0.217294,-0.404543,-0.182210,0.095108,0.143212,0.436753,-0.236939,0.569672,0.034064,-0.324481,0.039401,-0.055930,-0.026735,-0.044525,-0.031155,-0.045359,0.216065
348,-0.082725,1.140984,-0.198586,-0.787321,-0.361098,0.115784,0.208250,-0.020488,-0.274449,-0.856234,0.754018,-0.033097,-0.208073,-0.232977,0.228076,-0.190872,0.033426,0.280742,-0.000929,0.475858

In [24]:
ndf = pd.concat([ndf, y], axis = 1)
ndf

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,status_patient
0,0.507395,-0.421142,0.387359,-0.278536,-0.256417,-0.142587,0.524002,-0.058740,0.692328,-0.513301,...,-0.154673,-0.372326,0.063447,0.203476,-0.029339,0.080054,0.230352,0.796531,-0.240772,1
1,-0.913338,0.469680,-0.897301,0.516064,0.090262,0.497239,0.621075,-0.086860,0.133382,0.429461,...,-0.458448,0.374120,-0.158740,-0.016830,-0.390028,-0.169044,-0.279533,0.069854,0.036733,1
2,0.941651,1.135893,-0.037524,-0.773436,-0.164629,0.358867,-0.304602,-0.485169,-0.876215,-0.409627,...,0.077079,0.381671,-0.126444,0.175365,0.071274,0.162689,0.224261,0.033812,0.427166,1
3,-0.485110,0.951573,-0.114926,0.300021,0.658008,-0.455769,-0.727300,-0.448736,-0.416970,-0.108712,...,-0.129338,0.247061,-0.112766,-0.044348,0.193446,-0.194722,-0.257878,0.049161,-0.170757,1
4,0.601519,-0.528808,0.330653,-0.170536,-0.526976,-0.289042,0.376571,0.071930,0.079052,0.315951,...,-0.333416,0.457902,0.236440,-0.114730,-0.240092,-0.016232,-0.234302,-0.079925,0.217646,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,-0.715636,0.844186,0.210698,-0.527063,-0.621953,0.545056,0.055477,0.114063,0.486307,-0.182243,...,-0.338829,-0.401306,0.086131,0.039344,-0.104345,-0.041844,-0.050511,-0.155663,-0.145967,1
345,-0.761061,-0.283822,0.736366,-0.275418,-0.178385,-0.129462,0.489464,0.128567,0.204991,-0.060175,...,-0.086530,0.095372,0.038188,0.047724,0.024195,0.038740,-0.036529,0.005869,0.089886,0
346,-0.172933,0.545468,-0.276553,-0.631550,-0.470432,0.603202,0.171805,0.638355,0.791530,-0.395017,...,0.043759,-0.170708,-0.105080,0.269490,0.272448,0.049849,-0.268003,-0.048852,-0.063767,0
347,-0.069601,-0.202773,0.713319,-0.217294,-0.404543,-0.182210,0.095108,0.143212,0.436753,-0.236939,...,0.034064,-0.324481,0.039401,-0.055930,-0.026735,-0.044525,-0.031155,-0.045359,0.216065,1
348,-0.082725,1.140984,-0.198586,-0.787321,-0.361098,0.115784,0.208250,-0.020488,-0.274449,-0.856234,...,-0.033097,-0.208073,-0.232977,0.228076,-0.190872,0.033426,0.280742,-0.000929,0.475858,1

In [25]:
ndf.to_csv('pca.csv')